# Carregamento do Dataset e Exploração dos dados

## Importação das bibliotecas

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

## Importação do dataset

In [12]:
base_hotel = pd.read_csv('datasets/Hotel Reservations.csv')
base_hotel.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

In [13]:
base_hotel.describe()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests
count,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000
mean,1.844962,0.105279,0.810724,2.204300,0.030986,85.232557,2017.820427,7.423653,15.596995,0.025637,0.023349,0.153411,103.423539,0.619655
std,0.518715,0.402648,0.870644,1.410905,0.173281,85.930817,0.383836,3.069894,8.740447,0.158053,0.368331,1.754171,35.089424,0.786236
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2017.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,1.000000,0.000000,17.000000,2018.000000,5.000000,8.000000,0.000000,0.000000,0.000000,80.300000,0.000000
50%,2.000000,0.000000,1.000000,2.000000,0.000000,57.000000,2018.000000,8.000000,16.000000,0.000000,0.000000,0.000000,99.450000,0.000000
75%,2.000000,0.000000,2.000000,3.000000,0.000000,126.000000,2018.000000,10.000000,23.000000,0.000000,0.000000,0.000000,120.000000,1.000000
max,4.000000,10.000000,7.000000,17.000000,1.000000,443.000000,2018.000000,12.000000,31.000000,1.000000,13.000000,58.000000,540.000000,5.000000

In [14]:
base_hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36275 non-null  object
 1   no_of_adults                          36275 non-null  int64
 2   no_of_children                        36275 non-null  int64
 3   no_of_weekend_nights                  36275 non-null  int64
 4   no_of_week_nights                     36275 non-null  int64
 5   type_of_meal_plan                     36275 non-null  object
 6   required_car_parking_space            36275 non-null  int64
 7   room_type_reserved                    36275 non-null  object
 8   lead_time                             36275 non-null  int64
 9   arrival_year                          36275 non-null  int64
 10  arrival_month                         36275 non-null  int64
 11  arrival_date                          36275 non-null  int64
 12  market_segment_type                   36275 non-null  object
 13  repeated_guest                        36275 non-null  int64
 14  no_of_previous_cancellations          36275 non-null  int64
 15  no_of_previous_bookings_not_canceled  36275 non-null  int64
 16  avg_price_per_room                    36275 non-null  float64
 17  no_of_special_requests                36275 non-null  int64
 18  booking_status                        36275 non-null  object
dtypes: float64(1), int64(13), object(5)
memory usage: 5.3+ MB

## Exploração/manipulação dos dados

In [22]:
base_hotel = base_hotel.drop('booking_status', axis=1)

In [23]:
base_hotel = base_hotel.drop('Booking_ID', axis=1)

In [24]:
base_hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 17 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   no_of_adults                          36275 non-null  int64
 1   no_of_children                        36275 non-null  int64
 2   no_of_weekend_nights                  36275 non-null  int64
 3   no_of_week_nights                     36275 non-null  int64
 4   type_of_meal_plan                     36275 non-null  object
 5   required_car_parking_space            36275 non-null  int64
 6   room_type_reserved                    36275 non-null  object
 7   lead_time                             36275 non-null  int64
 8   arrival_year                          36275 non-null  int64
 9   arrival_month                         36275 non-null  int64
 10  arrival_date                          36275 non-null  int64
 11  market_segment_type                   36275 non-null  object
 12  repeated_guest                        36275 non-null  int64
 13  no_of_previous_cancellations          36275 non-null  int64
 14  no_of_previous_bookings_not_canceled  36275 non-null  int64
 15  avg_price_per_room                    36275 non-null  float64
 16  no_of_special_requests                36275 non-null  int64
dtypes: float64(1), int64(13), object(3)
memory usage: 4.7+ MB

In [25]:
base_hotel['label_avg_price_per_room'] = pd.cut(base_hotel['avg_price_per_room'],
                                        bins=[-float('inf'), 85, 115, float('inf')],
                                        labels=[0, 1, 2])

In [26]:
base_hotel = base_hotel.drop('avg_price_per_room', axis=1)

In [27]:
base_hotel

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,no_of_special_requests,label_avg_price_per_room
0,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,0,0
1,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,1,1
2,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,0,0
3,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,0,1
4,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,1,2
36271,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,2,1
36272,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,2,1
36273,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,0,1
36274,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,0,2

In [28]:
base_hotel.isnull().sum()

no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
no_of_special_requests                  0
label_avg_price_per_room                0
dtype: int64

In [29]:
colunas = []
colunas.append('label_avg_price_per_room')
for i in range(len(base_hotel.columns[:-1])):
    colunas.append(base_hotel.columns[i])
base_hotel = base_hotel[colunas]
base_hotel

,label_avg_price_per_room,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,no_of_special_requests
0,0,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,0
1,1,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,1
2,0,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,0
3,1,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,0
4,1,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,2,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,1
36271,1,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,2
36272,1,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,2
36273,1,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,0
36274,2,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,0

In [30]:
base_hotel = pd.get_dummies(base_hotel,prefix=['type_of_meal_plan', 'room_type_reserved', 'arrival_year', 'market_segment_type'],
                   columns=['type_of_meal_plan', 'room_type_reserved', 'arrival_year', 'market_segment_type'])

In [31]:
base_hotel = base_hotel.astype(int)
base_hotel

,label_avg_price_per_room,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_month,arrival_date,repeated_guest,...,room_type_reserved_Room_Type 5,room_type_reserved_Room_Type 6,room_type_reserved_Room_Type 7,arrival_year_2017,arrival_year_2018,market_segment_type_Aviation,market_segment_type_Complementary,market_segment_type_Corporate,market_segment_type_Offline,market_segment_type_Online
0,0,2,0,1,2,0,224,10,2,0,...,0,0,0,1,0,0,0,0,1,0
1,1,2,0,2,3,0,5,11,6,0,...,0,0,0,0,1,0,0,0,0,1
2,0,1,0,2,1,0,1,2,28,0,...,0,0,0,0,1,0,0,0,0,1
3,1,2,0,0,2,0,211,5,20,0,...,0,0,0,0,1,0,0,0,0,1
4,1,2,0,1,1,0,48,4,11,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,2,3,0,2,6,0,85,8,3,0,...,0,0,0,0,1,0,0,0,0,1
36271,1,2,0,1,3,0,228,10,17,0,...,0,0,0,0,1,0,0,0,0,1
36272,1,2,0,2,6,0,148,7,1,0,...,0,0,0,0,1,0,0,0,0,1
36273,1,2,0,0,3,0,63,4,21,0,...,0,0,0,0,1,0,0,0,0,1
36274,2,2,0,1,2,0,207,12,30,0,...,0,0,0,0,1,0,0,0,1,0

## Divisão para Treino e Teste

In [32]:
base_treinamento = base_hotel.iloc[0:25392,:]
base_treinamento.shape

(25392, 31)

In [33]:
base_treinamento

,label_avg_price_per_room,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_month,arrival_date,repeated_guest,...,room_type_reserved_Room_Type 5,room_type_reserved_Room_Type 6,room_type_reserved_Room_Type 7,arrival_year_2017,arrival_year_2018,market_segment_type_Aviation,market_segment_type_Complementary,market_segment_type_Corporate,market_segment_type_Offline,market_segment_type_Online
0,0,2,0,1,2,0,224,10,2,0,...,0,0,0,1,0,0,0,0,1,0
1,1,2,0,2,3,0,5,11,6,0,...,0,0,0,0,1,0,0,0,0,1
2,0,1,0,2,1,0,1,2,28,0,...,0,0,0,0,1,0,0,0,0,1
3,1,2,0,0,2,0,211,5,20,0,...,0,0,0,0,1,0,0,0,0,1
4,1,2,0,1,1,0,48,4,11,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25387,0,2,0,0,2,0,8,9,8,0,...,0,0,0,1,0,0,0,0,0,1
25388,1,2,0,0,2,0,257,7,1,0,...,0,0,0,1,0,0,0,0,1,0
25389,0,2,0,0,1,0,105,4,6,0,...,0,0,0,0,1,0,0,0,1,0
25390,1,1,0,1,1,0,100,4,18,0,...,0,0,0,0,1,0,0,0,0,1
25391,1,2,0,2,0,0,146,4,24,0,...,0,0,0,0,1,0,0,0,1,0

In [38]:
base_teste = base_hotel.iloc[25392:,:]
base_teste.shape
base_teste

,label_avg_price_per_room,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_month,arrival_date,repeated_guest,...,room_type_reserved_Room_Type 5,room_type_reserved_Room_Type 6,room_type_reserved_Room_Type 7,arrival_year_2017,arrival_year_2018,market_segment_type_Aviation,market_segment_type_Complementary,market_segment_type_Corporate,market_segment_type_Offline,market_segment_type_Online
25392,2,3,0,2,2,0,1,7,8,0,...,0,0,0,0,1,0,0,0,0,1
25393,1,1,0,1,0,0,5,3,6,0,...,0,0,0,0,1,0,0,0,1,0
25394,0,1,0,0,1,0,5,2,24,0,...,0,0,0,0,1,0,0,0,0,1
25395,2,1,0,0,3,0,71,6,14,0,...,0,0,0,0,1,0,0,0,1,0
25396,0,2,0,1,1,0,275,6,4,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,2,3,0,2,6,0,85,8,3,0,...,0,0,0,0,1,0,0,0,0,1
36271,1,2,0,1,3,0,228,10,17,0,...,0,0,0,0,1,0,0,0,0,1
36272,1,2,0,2,6,0,148,7,1,0,...,0,0,0,0,1,0,0,0,0,1
36273,1,2,0,0,3,0,63,4,21,0,...,0,0,0,0,1,0,0,0,0,1
36274,2,2,0,1,2,0,207,12,30,0,...,0,0,0,0,1,0,0,0,1,0

In [39]:
X_teste = base_teste.iloc[:, 1:len(base_hotel)].values
X_teste

array([[3, 0, 2, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [2, 0, 2, ..., 0, 0, 1],
       [2, 0, 0, ..., 0, 0, 1],
       [2, 0, 1, ..., 0, 1, 0]])

In [40]:
X_teste.shape

(10883, 30)

In [41]:
y_teste = base_teste.iloc[:, 0].values
y_teste

array([2, 1, 0, ..., 1, 1, 2])

In [42]:
y_teste.shape

(10883,)

## Exportação de treino e teste

In [43]:
base_treinamento.to_csv('hotel_train_xgboost.csv', header = False, index = False)
base_teste.to_csv('hotel_test_xgboost.csv', header = False, index = False)

# Treinamento Do XGBoost

In [50]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [52]:
hotel_train = pd.read_csv('hotel_train_xgboost.csv')

In [54]:
X_train = hotel_train.iloc[:, 1:].values  # Todas as colunas, exceto a primeira (que é a label)

In [55]:
y_train = hotel_train.iloc[:, 0].values   # Primeira coluna como a label

In [56]:
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=3)

In [57]:
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=3,
              num_parallel_tree=None, ...)

In [58]:
y_pred = xgb_model.predict(X_train)

In [59]:
print(f"Acurácia: {accuracy_score(y_train, y_pred)}")

Acurácia: 0.8913394509865701

In [61]:
print("Matriz de confusão:")
print(confusion_matrix(y_train, y_pred))

Matriz de confusão:
[[6608  880  104]
 [ 511 8867  673]
 [  48  543 7157]]

In [62]:
print("Relatório de classificação:")
print(classification_report(y_train, y_pred))

Relatório de classificação:
              precision    recall  f1-score   support

           0       0.92      0.87      0.90      7592
           1       0.86      0.88      0.87     10051
           2       0.90      0.92      0.91      7748

    accuracy                           0.89     25391
   macro avg       0.90      0.89      0.89     25391
weighted avg       0.89      0.89      0.89     25391

In [64]:
import joblib

In [66]:
joblib.dump(xgb_model, 'modelo_xgboost_treinado.pkl')

['modelo_xgboost_treinado.pkl']